### ISSUE TITLE
Doghouse server is broken after Github API changes

### ISSUE THREAD

**Issue by josephbergevin** [haya14busa/reviewdog#184]
I am trying to run golint on a subdirectory in my repo using this command:

`golint -set_exit_status ./pkg/... | reviewdog -f=golint -diff="git diff origin/master" -reporter=github-pr-check`

But it is giving me a `422 Invalid request` error - along with the message: `"annotation_level", "path" weren't supplied. []`

I can get this to run successfully by changing my command to this:

`cd pkg && golint -set_exit_status ./... | reviewdog -f=golint -diff="git diff origin/master" -reporter=github-pr-check`

But then the links referenced in the errors don't include the `pkg` folder, so they don't work.

I there a reviewdog flag I need to include to be able to make one of the above run commands work properly?

**Comment by josephbergevin** [comment]
Oh, interesting. Is there a specific issue filed?

**Comment by cupakromer** [comment]
Well I think this may be it for reviewdog. Otherwise, digging around I see that the [current GitHub v3 API for checks](https://developer.github.com/v3/checks/runs/#annotations-object) lists `annotation_level` and `path` as required fields for an `annotation` object.

Looks like changes were announced via the [GitHub blog on 2018-08-16](https://developer.github.com/changes/2018-08-16-changes-to-the-checks-rest-api/) and stated to take effect just the other day on the 27th (2018-08-27).

I think these are the change which caused the issue:

- `filename` is being renamed to `path`
- `warning_level` is being renamed to `annotation_level`

**Comment by josephbergevin** [comment]
I wonder why those are not being renamed when the linter is run on the project directory...

**Comment by josephbergevin** [comment]
@haya14busa wondering if I can get your take on this `422 Invalid request` error popping up...

**Comment by ruudk** [comment]
Getting the same issue today. When the checks report issues that are filtered (outside git diff) it does work. But when they are part of the git diff, it breaks.

**Comment by ruudk** [comment]
@josephbergevin Can you change the title of this issue? Something like "Doghouse server is broken after Github API changes"

**Comment by ruudk** [comment]
Btw, if the server code of Doghouse were to be open source, we could fix this issue 💪 ;)

**Comment by josephbergevin** [comment]
Yeah I came to the same roadblock. The fix definitely needs to happen in the doghouse server code.

**Comment by haya14busa** [comment]
I'm sincerely sorry for the very late response. I fixed it today so it should work fine now.
